apiVersion: v1
kind: Service
metadata:
  labels:
    run: markdownpy
  name: markdownpy-svc
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    run: markdownpy
  type: NodePort